[tool.black]
target-version = ["py310"]

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 120

[tool.pylint.MASTER]
# Temporary ignore until we are able to address issues on these:
ignore-paths = "^(demos/dynatrace-demo/fake_app.py|tests/|plugins/modules).*$"

[tool.pylint."MESSAGES CONTROL"]
disable = [
  "duplicate-code",
  "pointless-string-statement",
  "too-few-public-methods",
  "too-many-instance-attributes",
  "missing-module-docstring",
  "missing-class-docstring",
  "missing-function-docstring",
  "too-many-arguments",
  "too-many-branches",
  "inconsistent-return-statements",
  "invalid-name",
]
max-line-length=120

[tool.ruff.lint]
ignore = [ "E402" ]
