---
name: ✨ Feature request
description: Suggest an idea for this project
body:
  - type: markdown
    attributes:
      value: |
        Feature Request issues are for **feature requests** only.
        For debugging help or technical support, please see the [our ways of contact](https://ansible-rulebook.readthedocs.io/en/latest/contributing.html)

  - type: checkboxes
    id: terms
    attributes:
      label: Please confirm the following
      options:
        - label: I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
          required: true
        - label: I have checked the [current issues](https://github.com/ansible/ansible-rulebook/issues) for duplicates.
          required: true
        - label: I understand that ansible-rulebook is open source software provided for free and that I might not receive a timely response.
          required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature type
      description: >-
        What kind of feature is this?
      multiple: false
      options:
        - "New Feature"
        - "Enhancement to Existing Feature"
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: Briefly describe the desired enhancement.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: >-
        Describe the necessary steps to understand the scenario of the requested enhancement.
        Include all the steps that will help the developer and QE team understand what you are requesting.
    validations:
      required: true

  - type: textarea
    id: current-results
    attributes:
      label: Current results
      description: What is currently happening on the scenario?
    validations:
      required: true

  - type: textarea
    id: suggested-results
    attributes:
      label: Suggested feature result
      description: What is the result this new feature will bring?
    validations:
      required: true

  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
      description: Please provide any other information you think is relevant that could help us understand your feature request.
    validations:
      required: false
