---
- name: Listen for changes in pods on a Kubernetes cluster
  hosts: localhost
  sources:
    - name: Check for deployments in the cluster
      ansible.eda.kubernetes:
        api: AppsV1Api
        method: list_namespaced_deployment
        params:
          namespace: nginx-deployment-namespaced
  rules:
    - name: A deployment condition matched
      condition: event.type == "ADDED"
      action:
        run_playbook:
          name: example_playbook.yml
