---
- name: Controller Demo
  hosts: all
  sources:
    - ansible.eda.range:
        limit: 5
  rules:
    - name: Controller Rule
      condition: event.i == 1
      action:
        run_job_template:
          name: Demo Job Template
          organization: Default
...
