---
- name: Listen for events on a rabbitmq
  hosts: all
  sources:
    - ansible.eda.rabbitmq:
        host: localhost
        port: 5672
        queue: hello
  rules:
    - name: Event name is world
      action: event.name == "world"
        debug:
