---
# See https://github.com/ansible/team-devtools/blob/main/.github/workflows/ack.yml
name: ack
on:
  pull_request_target:
    types: [opened, labeled, unlabeled, synchronize]

permissions:
  checks: write
  contents: write # needed to update release
  pull-requests: write # pr approval and merge

jobs:
  ack:
    uses: ansible/team-devtools/.github/workflows/ack.yml@main
    secrets: inherit
