---
name: Scheduled full tests

on:
  schedule:
    # Run at 10:00 AM/PM UTC
    - cron: "0 10,22 * * *"
  # Run on demand
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

env:
  ANSIBLE_FORCE_COLOR: 1
  FORCE_COLOR: 1 # tox, pytest
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PY_COLORS: 1

jobs:
  prepare:
    name: prepare
    runs-on: ubuntu-24.04
    outputs:
      matrix: ${{ steps.generate_matrix.outputs.matrix }}
    steps:
      - name: Determine matrix
        id: generate_matrix
        uses: ansible/actions/matrix@v0
        with:
          min_python: "3.9"
          max_python: "3.12"
          default_python: "3.9"
          other_names: |
            py39:tox -e py39-unit;tox -e py39-integration;tox -e coverage
            py310:tox -e py310-unit;tox -e py310-integration;tox -e coverage
            py311:tox -e py311-unit;tox -e py311-integration;tox -e coverage
            py312:tox -e py312-unit;tox -e py312-integration;tox -e coverage
          platforms: linux
          skip_explode: "1"

  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os || 'ubuntu-24.04' }}
    needs:
      - prepare
    defaults:
      run:
        shell: ${{ matrix.shell || 'bash'}}
        working-directory: ansible_collections/ansible/eda
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.prepare.outputs.matrix) }}
    steps:

      - uses: actions/checkout@v6
        with:
          fetch-depth: 0 # needed by setuptools-scm
          path: ansible_collections/ansible/eda
          submodules: true

      - name: Install package dependencies (ubuntu)
        if: ${{ contains(matrix.os, 'ubuntu') }}
        run: |
          sudo apt-get -qq -o Dpkg::Use-Pty=0 remove -y docker-compose
          sudo apt-get -qq -o Dpkg::Use-Pty=0 update -y --fix-missing
          sudo apt-get -qq -o Dpkg::Use-Pty=0 --assume-yes --no-install-recommends install -y apt-transport-https curl libsystemd0 libsystemd-dev pkg-config libkrb5-dev krb5-user sscg
          sudo add-apt-repository ppa:deadsnakes/ppa
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get -qq -o Dpkg::Use-Pty=0 update -y --fix-missing
          sudo apt-get -qq -o Dpkg::Use-Pty=0 install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin shellcheck
          # Do not install docker-compose-plugin because it would v1 (broken due to not working with newer requests library)
          sudo systemctl enable --now docker
          sudo curl -sL "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Install Java
        uses: actions/setup-java@v5
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Set up Python ${{ matrix.python_version || '3.10' }}
        uses: actions/setup-python@v6
        with:
          cache: pip
          python-version: ${{ matrix.python_version || '3.10' }}
          cache-dependency-path: "*requirements*.txt"

      - name: Install tox
        run: |
          python3 -m pip install --upgrade pip wheel tox

      - run: ${{ matrix.command }}

      - run: ${{ matrix.command2 }}
        if: ${{ matrix.command2 }}

      - run: ${{ matrix.command3 }}
        if: ${{ matrix.command3 }}

      - run: ${{ matrix.command4 }}
        if: ${{ matrix.command4 }}

      - run: ${{ matrix.command5 }}
        if: ${{ matrix.command5 }}

      - name: Notify to slack if failure
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: GH Slack Notifier for EDA
          SLACK_TITLE: Failure of scheduled tests for event-driven-ansible
          SLACK_MESSAGE: |
            Scheduled tests for event-driven-ansible failed.
            Job: ${{ matrix.name }}
            Id: ${{ github.run_id }}"
            Workflow: ${{ github.workflow }}
